"use client";

import Image from "next/image";
import { FadeIn } from "./Shared";
import { PageHero, Section, Card, DotList, DayPage } from "./PageShell";
import { ArchHorizon } from "./Illustrations";
import { KAI_SRC_SM } from "./KaiGuide";

const CREDENTIALS = [
  "BPS Certification as a Psychological Assessor (British Psychological Society) — the gold standard in assessment credibility",
  "CIPD Diploma in Human Resources Management and Subject Matter Expert status",
  "Advanced training in psychometric tools including Korn Ferry, Hogan, Saville, MBTI, PAPI-3, and more",
  "20+ years designing behavioral assessments for major international organizations, governments, and institutions across the Middle East",
];

const PHASES = [
  {
    phase: "Phase 1",
    when: "Now",
    body: "Launch the CORE assessment and gather data.",
    active: true,
  },
  {
    phase: "Phase 2",
    when: "Next",
    body: "Validate CORE against established frameworks, publish research, expand to university partnerships.",
  },
  {
    phase: "Phase 3",
    when: "Then",
    body: "Advanced features — career matching, skill gap analysis, AI advisor — more countries, and completed PhD research.",
  },
];

export const About = () => (
  <DayPage>
    <main>
      <PageHero
        eyebrow="About Us"
        title="Career guidance shouldn’t be"
        accent="a privilege."
        lede="Tareeq exists to democratize access to science-based career guidance for every young person in the MENA region."
        art={ArchHorizon}
        artClass="w-48 h-auto"
      />

      <Section
        eyebrow="Why we built Tareeq"
        title="A gap worth"
        accent="closing."
      >
        <FadeIn className="max-w-3xl">
          <div className="space-y-5 text-[var(--day-ink-2)] leading-relaxed">
            <p>
              After 20+ years in human capital development, Enas observed a gap:
              young people in the MENA region were using career assessment tools
              designed for Western contexts. These tools asked abstract
              questions that didn’t fit their experience. They focused only on
              interests, ignoring other crucial factors. And they didn’t account
              for regional job markets, educational systems, or cultural
              context.
            </p>
            <p>
              The result? Young people in MENA were making major life decisions
              — choosing university programs, committing to career paths —
              without guidance truly relevant to their situation.
            </p>
            <p className="font-heading text-lg font-semibold text-[#B07A18]">
              Tareeq changes that. Built specifically for youth in the MENA
              region, by someone who understands both career psychology and
              regional context.
            </p>
          </div>
        </FadeIn>
      </Section>

      <Section
        eyebrow="Founder"
        title="Enas Elgarhy,"
        accent="Founder & Lead Assessor."
        className="border-t border-[var(--day-line)]"
      >
        <FadeIn>
          <div className="rounded-story-alt p-px bg-gradient-to-br from-[#F4C660]/70 via-[#C8B6F0]/40 to-transparent max-w-4xl">
            <div className="rounded-story-alt bg-[var(--day-elevated)] p-8 sm:p-12">
              <DotList items={CREDENTIALS} />
              <p className="mt-6 text-[15px] text-[var(--day-ink-2)] leading-relaxed">
                She designed CORE because she saw a need and believed she could
                fill it. And she’s building Tareeq as her PhD research platform
                — meaning the data generated by the platform will advance
                academic knowledge about career development in the MENA region.
              </p>
            </div>
          </div>
        </FadeIn>
      </Section>

      <Section
        eyebrow="Our vision"
        title="Where this"
        accent="is going."
        className="border-t border-[var(--day-line)]"
      >
        <FadeIn className="max-w-3xl mb-12">
          <p className="text-[var(--day-ink-2)] leading-relaxed">
            In 3–5 years, Tareeq will be the platform every young person in MENA
            uses for career guidance. In 5–10 years, we’ll have comprehensive
            research on career development patterns specific to the region —
            knowledge that shapes how educators, policymakers, and students
            think about career choice.
          </p>
        </FadeIn>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {PHASES.map((p, i) => (
            <FadeIn key={p.phase} delay={i * 0.1}>
              <Card className={`h-full ${p.active ? "!border-[#F4C660]" : ""}`}>
                <div className="flex items-center justify-between">
                  <span
                    className={`font-heading font-semibold ${p.active ? "text-[#B07A18]" : "text-[#6D5BA8]"}`}
                  >
                    {p.phase}
                  </span>
                  <span className="text-xs uppercase tracking-widest text-[var(--day-ink-3)]">
                    {p.when}
                  </span>
                </div>
                <p className="mt-3 text-sm text-[var(--day-ink-2)] leading-relaxed">
                  {p.body}
                </p>
              </Card>
            </FadeIn>
          ))}
        </div>
      </Section>

      <Section
        eyebrow="Questions? Feedback?"
        title="We read"
        accent="every message."
        className="border-t border-[var(--day-line)]"
      >
        <FadeIn>
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-6 max-w-3xl">
            <span className="relative shrink-0 w-16 h-16 rounded-full overflow-hidden ring-2 ring-[#F4C660]/70 bg-gradient-to-b from-[#C8B6F0]/40 to-[#F4C660]/30">
              <Image
                src={KAI_SRC_SM}
                alt="Kai, Tareeq’s AI guide"
                width={96}
                height={96}
                className="absolute w-[170%] max-w-none left-1/2 -translate-x-1/2 top-[-6%]"
              />
            </span>
            <div>
              <p className="text-[var(--day-ink-2)] leading-relaxed">
                Tell us what works, what doesn’t, what you’d like to see. Your
                input shapes how we develop.
              </p>
              <a
                href="mailto:support@tareek.me"
                className="mt-2 inline-block text-lg font-medium text-[#6D5BA8] hover:text-[#B07A18] transition-colors"
              >
                support@tareek.me
              </a>
            </div>
          </div>
        </FadeIn>
      </Section>
    </main>
  </DayPage>
);
