/**
 * ScoringSpec — the deterministic, backend-executed specification a *Custom*
 * assessment is scored against.
 *
 * Whether a spec is authored in the Manual Builder or generated by AI from
 * uploaded documents, its shape is identical, and the executor
 * (`lib/scoring/spec-executor.ts`) does not care which path produced it. This
 * is the structural guarantee behind the product's core principle:
 *
 *   AI generates the specification. The backend executes the scoring.
 *   AI never scores a user.
 *
 * Cluster keys are plain `string`s (NOT the Core `ClusterCode` union from
 * `./types`): a Custom assessment may define its own cluster taxonomy, so the
 * rule engine stays decoupled from the Core engine's fixed eight clusters.
 */

export type RuleOperator = "=" | "!=" | ">" | "<" | ">=" | "<=";
export type RuleCombinator = "AND" | "OR";

/**
 * How a profile is selected from category scores:
 *  - `first_match`     — first rule (by priority, then id) whose conditions pass.
 *                        Covers threshold rules AND category-vs-category rules.
 *  - `highest_score_wins` — the category with the highest total wins; the profile
 *                        whose `categoryCode` matches that category is returned.
 */
export type ScoringStrategy = "first_match" | "highest_score_wins";

/** Per-cluster point totals derived from a user's answers (a.k.a. categoryScores). */
export type ClusterTotals = Record<string, number>;

export interface RuleCondition {
  /** Category/cluster code being tested, e.g. "LEAD". */
  cluster: string;
  operator: RuleOperator;
  /** Right-hand side as a constant (used when `valueCategory` is unset). */
  value?: number;
  /**
   * Right-hand side as ANOTHER category's total — enables comparisons like
   * "TECH > LEAD". When set, it takes precedence over `value`.
   */
  valueCategory?: string;
}

export interface ResultRule {
  id: string;
  /** Profile assigned when this rule matches. */
  resultProfileId: string;
  /** How the conditions combine. */
  combinator: RuleCombinator;
  conditions: RuleCondition[];
  /** Lower fires first; ties are broken by `id` so ordering is total. */
  priority: number;
}

/** A localised list, e.g. `{ en: ["Computer Science"], ar: ["علوم الحاسب"] }`. */
export type LocalizedList = Record<string, string[]>;

export interface SpecResultProfile {
  id: string;
  /** Stable, human-readable code unique within the assessment, e.g. "LEADER". */
  code?: string;
  /** Bilingual title (title_en / title_ar). */
  name: Record<string, string>;
  /** Bilingual description (description_en / description_ar). */
  description?: Record<string, string>;
  /**
   * The category this profile represents — used by `highest_score_wins` to map
   * the top-scoring category to its profile.
   */
  categoryCode?: string;
  recommendedMajors?: LocalizedList;
  recommendedCareers?: LocalizedList;
  strengths?: LocalizedList;
  developmentAreas?: LocalizedList;
  color?: string;
  icon?: string;
  /** Returned when no rule matches. At most one profile per spec sets this. */
  isFallback?: boolean;
}

export interface SpecClusterDef {
  code: string;
  name: Record<string, string>;
  /** Total points available for this cluster (display / normalisation only). */
  maxScore?: number;
}

export interface ScoringSpec {
  version: number;
  /** Selection strategy; defaults to `"first_match"` when omitted (back-compat). */
  strategy?: ScoringStrategy;
  clusters: SpecClusterDef[];
  profiles: SpecResultProfile[];
  rules: ResultRule[];
}

export interface ConditionResult {
  cluster: string;
  operator: RuleOperator;
  value: number;
  actual: number;
  passed: boolean;
}

export interface RuleEvaluation {
  ruleId: string;
  resultProfileId: string;
  priority: number;
  matched: boolean;
  conditionResults: ConditionResult[];
}

/** How the winning profile was determined. */
export type MatchSource = "rule" | "highest_score" | "fallback" | "none";

export interface SpecOutcome {
  /** Matched (or fallback) profile id; null when neither matched nor a fallback exists. */
  resultProfileId: string | null;
  /** The resolved winning profile object (convenience; null when none). */
  winningProfile: SpecResultProfile | null;
  matchedRuleId: string | null;
  /** Which mechanism selected the profile. */
  matchedBy: MatchSource;
  /** Retained for back-compat: true iff `matchedBy === "fallback"`. */
  matchedByFallback: boolean;
  /** Per-category totals (a.k.a. categoryScores). */
  clusterTotals: ClusterTotals;
  /** Ordered audit trail of every rule evaluated, up to and including the match. */
  evaluation: RuleEvaluation[];
}
